{
 "title": "CPU-USAGE",
 "tags": [ "final" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "pods ready",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{namespace=\"tp-final\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Usage workers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * rate(\r\n  container_cpu_usage_seconds_total{namespace=\"tp-final\",pod=~\"worker.*\"}[5m]\r\n)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_usage_bytes{namespace=\"tp-final\"}\r\n)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (tp-final)",
   "type": "timeseries",
   "description": "CPU Usage (tp-final)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"tp-final\"}[5m])\r\n) * 100\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}