apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-sa-secret
  namespace: tp-final
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: gcp-sa-secret
    creationPolicy: Owner
  data:
    - secretKey: key.json
      remoteRef:
        key: gcp-sa
        property: key
