apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
  namespace: tp-final
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: rabbitmq
        property: user
    - secretKey: password
      remoteRef:
        key: rabbitmq
        property: password
