apiVersion: v1
kind: Pod
metadata:
  name: test-secrets-pod
  namespace: tp-final
spec:
  restartPolicy: Never
  containers:
    - name: tester
      image: busybox
      command: ["sleep", "3600"]
      # Inyectamos RabbitMQ como variables de entorno
      env:
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: user
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
      # Montamos el JSON de GCP SA como volumen
      volumeMounts:
        - name: gcp-sa-volume
          mountPath: /etc/gcp
          readOnly: true
  volumes:
    - name: gcp-sa-volume
      secret:
        secretName: gcp-sa-secret
        items:
          - key: key.json
            path: key.json
