version: '3.8'

services:
  node_c:
    build: ./node_c
    container_name: ${NODE_NAME}
    environment:
      - NODE_NAME=${NODE_NAME}
      - D_HOST=node_d
      - D_PORT=4000
    restart: always
    volumes:
      - ./logs/:/app/logs
    networks:
      - hit6_network

networks:
  hit6_network:
    external: true