# backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/blockchainsd2025/backend:latest
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-password
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: gcp-sa-vol
          mountPath: /etc/gcp
          readOnly: true
      volumes:
      - name: gcp-sa-vol
        secret:
          secretName: gcp-sa-secret
          items:
          - key: key.json
            path: key.json
