apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  labels:
    app: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: gcr.io/blockchainsd2025/coordinator:latest
        ports:
        - containerPort: 11111
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        volumeMounts:
        - name: gcp-sa-vol
          mountPath: /etc/gcp
          readOnly: true
      volumes:
      - name: gcp-sa-vol
        secret:
          secretName: gcp-sa-secret
          items:
          - key: key.json
            path: key.json
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  selector:
    app: coordinator
  ports:
  - protocol: TCP
    port: 11111
    targetPort: 11111
  type: LoadBalancer
