apiVersion: apps/v1
kind: Deployment
metadata:
  name: split
  labels:
    app: split
spec:
  replicas: 1
  selector:
    matchLabels:
      app: split
  template:
    metadata:
      labels:
        app: split
    spec:
      containers:
        - name: split
          image: gcr.io/blockchainsd2025/split:latest
          ports:
            - containerPort: 5001
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: split
spec:
  selector:
    app: split
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
