apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-mock
  labels:
    app: worker-mock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-mock
  template:
    metadata:
      labels:
        app: worker-mock
    spec:
      containers:
        - name: worker-mock
          image: gcr.io/blockchainsd2025/worker_mock:latest
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
            - name: COORDINATOR_URL
              value: "http://coordinator:11111"
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
