version: '3.8'

services:
  server:
    build: ./server
    container_name: servidor_tcp
    ports:
      - "12345:12345"
  
  client:
    build: ./client
    container_name: cliente_tcp
    depends_on:
      - server

  tests:
    build: ./tests
    container_name: test_tcp
    depends_on:
      - server
