apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mover
  name: mover
  namespace: pilar3-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mover
  template:
    metadata:
      labels:
        app: mover
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: redis-secret
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              key: RABBITMQ_USER
              name: rabbitmq-secret
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              key: RABBITMQ_PASS
              name: rabbitmq-secret
        envFrom:
        - configMapRef:
            name: blockchain-config
        - secretRef:
            name: blockchain-secrets
        - configMapRef:
            name: system-config
        image: gcr.io/blockchainsd2025/mover:latest
        name: mover
      nodeSelector:
        node-type: app
