apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-mock-1
  namespace: pilar3-test
  labels:
    app: worker-mock-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-mock-1
  template:
    metadata:
      labels:
        app: worker-mock-1
    spec:
      containers:
        - name: worker-mock
          image: gcr.io/blockchainsd2025/worker-mock-1:latest
          env:
            - name: WORKER_NAME
              value: worker-mock-1
            - name: TARGET_SUFFIX
              value: "12"
          envFrom:
            - configMapRef:
                name: blockchain-config
            - secretRef:
                name: blockchain-secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-mock-2
  namespace: pilar3-test
  labels:
    app: worker-mock-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-mock-2
  template:
    metadata:
      labels:
        app: worker-mock-2
    spec:
      containers:
        - name: worker-mock
          image: gcr.io/blockchainsd2025/worker-mock-2:latest
          env:
            - name: WORKER_NAME
              value: worker-mock-2
            - name: TARGET_SUFFIX
              value: "12"
          envFrom:
            - configMapRef:
                name: blockchain-config
            - secretRef:
                name: blockchain-secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-mock-3
  namespace: pilar3-test
  labels:
    app: worker-mock-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-mock-3
  template:
    metadata:
      labels:
        app: worker-mock-3
    spec:
      containers:
        - name: worker-mock
          image: gcr.io/blockchainsd2025/worker-mock-3:latest
          env:
            - name: WORKER_NAME
              value: worker-mock-3
            - name: TARGET_SUFFIX
              value: "12"
          envFrom:
            - configMapRef:
                name: blockchain-config
            - secretRef:
                name: blockchain-secrets
