
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        role: app
      containers:
        - name: backend
          image: gcr.io/alert-parsec-456902-u3/sobel-backend:latest
