apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        role: app
      containers:
        - name: frontend
          image: gcr.io/alert-parsec-456902-u3/sobel-frontend:latest
          ports:
          - containerPort: 80   # <- esto tiene que estar
