apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      nodeSelector:
        role: app
      containers:
        - name: worker
          image: gcr.io/alert-parsec-456902-u3/sobel-worker:latest
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: REDIS_HOST
              value: "redis"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "300m"
