{
 "title": "Kubernetes Cluster FINAL FINAL FINAL",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": ".*" },
   { "name": "namespace", "query": "pilar3-test" }
  ]
 },
 "panels": [
  {
   "title": "RABBIT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_connections{job=\"rabbitmq-exporter\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "largo cola",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_global{job=\"rabbitmq-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deliver Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_messages_deliver_rate{job=\"rabbitmq-exporter\"}[1m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Publish Rate\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_messages_publish_rate{job=\"rabbitmq-exporter\"}[1m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Ready by Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{job=\"rabbitmq-exporter\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Uso de mem-cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memoria real por pod",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  container_memory_usage_bytes{namespace=\"pilar3-test\"}\r\n) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU real por pod",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by(pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"pilar3-test\"}[1m])\r\n)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Cluster Pod Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size{nodename=~\"$node\"}) - sum (node_filesystem_free{nodename=~\"$node\"})) / sum (node_filesystem_size{nodename=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size{nodename=~\"$node\"}) - sum(node_filesystem_free{nodename=~\"$node\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size{nodename=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}