apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-rabbitmq-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: rabbitmq-exporter
  namespaceSelector:
    matchNames:
      - pilar3-test
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
