apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
  namespace: pilar3-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_USER
      remoteRef:
        key: secret/rabbitmq
        property: RABBITMQ_USER
    - secretKey: RABBITMQ_PASS
      remoteRef:
        key: secret/rabbitmq
        property: RABBITMQ_PASS
