name: Deploy Mover (Exchanger)

on:
  push:
    paths:
      - 'tpFinal/Pilar2/exchanger/**'
      - '.github/workflows/02-mover.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del repositorio
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: blockchainsd2025
          install_components: gke-gcloud-auth-plugin

      - name: Configure Docker to use gcloud for gcr.io
        run: gcloud auth configure-docker gcr.io --quiet

      - name: 🔐 Autenticación con GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          gcloud config set project blockchainsd2025 --quiet
          gcloud auth configure-docker gcr.io --quiet

      - name: 🛠️ Build y Push Docker image mover
        run: |
          docker build \
            -t gcr.io/blockchainsd2025/mover:latest \
            -f tpFinal/Pilar2/exchanger/deploy/Dockerfile \
            tpFinal/Pilar2/exchanger
          docker push gcr.io/blockchainsd2025/mover:latest

      - name: ☸️ Despliegue en GKE del Mover
        run: |
          gcloud container clusters get-credentials blockchain-cluster \
            --zone=southamerica-east1-a \
            --project=blockchainsd2025
          kubectl apply -f tpFinal/pilar3-test-k8s/04-mover.yaml
