name: Deploy Validator
on:
  push:
    paths:
      - 'Pilar2/validator/**'
      - '.github/workflows/03-validator.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout del repositorio
        uses: actions/checkout@v3

      - name: 🔐 Autenticación con GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          cat Pilar3/infra/secrets/terraform-key.json > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project blockchainsd2025 --quiet
          gcloud auth configure-docker gcr.io --quiet

      - name: 🛠️ Build y Push Docker image Validator
        run: |
          docker build \
            -t gcr.io/blockchainsd2025/validator:latest \
            -f Pilar2/validator/deploy/Dockerfile \
            Pilar2/validator
          docker push gcr.io/blockchainsd2025/validator:latest

      - name: ☸️ Despliegue en GKE del Validator
        run: |
          gcloud container clusters get-credentials blockchain-cluster \
            --zone=southamerica-east1-a \
            --project=blockchainsd2025
          kubectl apply -f pilar3-test-k8s/05-validator.yaml
