name: Deploy Worker Mocks
on:
  push:
    paths:
      - 'Pilar2/worker_mock/**'
      - '.github/workflows/05-worker-mocks.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout del repositorio
        uses: actions/checkout@v3

      - name: 🔐 Autenticación con GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
      - name: 🔐 Escribir clave de GCP desde secrets
        run: echo "${{ secrets.GCP_SA_KEY }}" > key.json
      - name: 🔐 Autenticación con GCP
        run: |
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker gcr.io --quiet
      - name: 🛠️ Build y Push Docker image Worker Mock
        run: |
          docker build \
            -t gcr.io/blockchainsd2025/worker-mock:latest \
            -f Pilar2/worker_mock/deploy/Dockerfile \
            Pilar2/worker_mock
          docker push gcr.io/blockchainsd2025/worker-mock:latest

      - name: ☸️ Despliegue en GKE de Worker Mocks
        run: |
          gcloud container clusters get-credentials blockchain-cluster \
            --zone=southamerica-east1-a \
            --project=blockchainsd2025
          kubectl apply -f pilar3-test-k8s/07-worker-mocks.yaml
