name: Deploy Frontend
on:
  push:
    paths:
      - 'tpFinal/pilar3-test-k8s/frontend/**'
      - '.github/workflows/06-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout del repositorio
        uses: actions/checkout@v3

      - name: 🔐 Autenticación con GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          cat tpFinal/Pilar3/tpFinal/infra/secrets/terraform-key.json > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project blockchainsd2025 --quiet
          gcloud auth configure-docker gcr.io --quiet

      - name: 🛠️ Build y Push Docker image Frontend
        run: |
          docker build \
            -t gcr.io/blockchainsd2025/frontend:latest \
            -f tpFinal/pilar3-test-k8s/frontend/Dockerfile \
            tpFinal/pilar3-test-k8s/frontend
          docker push gcr.io/blockchainsd2025/frontend:latest

      - name: ☸️ Despliegue en GKE del Frontend
        run: |
          gcloud container clusters get-credentials blockchain-cluster \
            --zone=southamerica-east1-a \
            --project=blockchainsd2025
          kubectl apply -f tpFinal/pilar3-test-k8s/08-frontend.yaml
